name: Deploy to dev

on: workflow_dispatch

jobs:
  dev_deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: Check formatting with Prettier
      - name: Check formatting with Prettier
        run: npx prettier --check .

      # Step 3: Initialize (AWS setup)
      - uses: ./.github/actions/initialize
        with:
          aws_access_key: ${{ secrets.MIRA_AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.MIRA_AWS_SECRET_ACCESS_KEY }}

      # Step 4: Deploy static site to S3 bucket
      - name: Deploy static site to S3 bucket
        env:
          BUCKET_NAME: "miraly-dev-website"
        run: aws s3 sync ./out/ s3://${{ env.BUCKET_NAME }} --delete

      # Step 5: Invalidate CloudFront
      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ secrets.DEV_CLOUD_FRONT_DISTRIBUTION_ID }}
          PATHS: "/*"
